app = "wa-recap-bot"
primary_region = "sin"

[experimental]
  auto_rollback = true
  primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[mounts]
  source = "wwebjs_data"
  destination = "/app/.wwebjs_auth"

[vm]
  size = "shared-cpu-1x"
  memory = 1024
