app = 'wa-recap-bot'
primary_region = 'sin'

[experimental]
  auto_rollback = true

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = []
    port = 3000

  [services.concurrency]
    type = "connections"
    hard_limit = 50
    soft_limit = 25

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
  