app = "wa-recap-bot"
primary_region = "sin"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[mounts]
  source = "wwebjs_data"
  destination = "/app/.wwebjs_auth"