# fly.toml app configuration file generated for wa-recap-bot on 2025-06-19T20:14:34+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wa-recap-bot"
primary_region = "sin"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
