name: Scale Up Bot (06:00 WITA)

on:
  schedule:
    - cron: '0 23 * * *'  # UTC 22:00 = 07:00 WITA
  workflow_dispatch:      # bisa juga dijalankan manual

jobs:
  scale:
    runs-on: ubuntu-latest
    steps:
      - name: Install flyctl
        run: |
          curl -L https://fly.io/install.sh | sh
          export PATH="$HOME/.fly/bin:$PATH"
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Scale up to shared-cpu-2x
        run: flyctl scale vm shared-cpu-2x --memory 1024 --app wa-recap-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
