name: Scale Up Bot (06:00 WITA)

on:
  schedule:
    - cron: '0 22 * * *'  # UTC 22:00 = 06:00 WITA
  workflow_dispatch:      # bisa juga dijalankan manual

jobs:
  scale:
    runs-on: ubuntu-latest
    steps:
      - name: Scale up to shared-cpu-2x
        run: flyctl scale vm shared-cpu-2x --memory 1024 --region sin --app wa-recap-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
