name: Scale Down to CPU 1x (19:00 WITA)

on:
  schedule:
    - cron: '0 11 * * *'  # UTC 11:00 = WITA 19:00
  workflow_dispatch:

jobs:
  scale-down:
    runs-on: ubuntu-latest
    steps:
      - name: Scale to shared-cpu-1x
        run: flyctl scale vm shared-cpu-1x --memory 1024 --region sin --app wa-recap-bot
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
